board: MKS DLC32 MAX V1.1
name: SRcnc
meta: 2026-07-12 DLC32 MAX V1.1 (ESP32-S3) with DM542T drivers

kinematics:
  Cartesian:

stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 2

# Pendant (RJ11/RJ12 telephone jack)
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.18
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 1000000
  mode: 8N1

uart_channel1:
  report_interval_ms: 75
  uart_num: 1

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.14
  sck_pin: gpio.13

sdcard:
  cs_pin: NO_PIN
  card_detect_pin: NO_PIN

axes:
  shared_stepper_disable_pin: gpio.8

  x:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 800.000
    acceleration_mm_per_sec2: 20.000
    max_travel_mm: 220.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.39:low:pu
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        step_pin: gpio.16
        direction_pin: gpio.15:low

  y:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 800.000
    acceleration_mm_per_sec2: 20.000
    max_travel_mm: 380.000
    soft_limits: true
    homing:
      cycle: 3
      positive_direction: true
      mpos_mm: 380.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_pos_pin: gpio.40:low:pu
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        step_pin: gpio.7
        direction_pin: gpio.6:low

  z:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 400.000
    acceleration_mm_per_sec2: 20.000
    max_travel_mm: 95.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_pos_pin: gpio.41:low:pu
      hard_limits: true
      pulloff_mm: 3.000
      stepstick:
        step_pin: gpio.5
        direction_pin: gpio.4:low

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

probe:
  # HLTNC 3D Touch Probe (dedicated probe connector)
  pin: gpio.37:low:pu
  # Auto-zero Z touch plate (on Flame sensor connector)
  toolsetter_pin: gpio.36:low:pu
  check_mode_start: true

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

# spindle PWM signal
PWM:
  pwm_hz: 2500
  output_pin: gpio.2:high
  enable_pin: gpio.35
  s0_with_disable: true
  tool_num: 0
  spinup_ms: 4000
  spindown_ms: 4000
  speed_map: 0=0.000% 12000=100.000%

start:
  must_home: false
